### ISSUE TITLE
Permission denied when creating a Spring Boot based function

### ISSUE THREAD

**Issue by wei-qiang** [projectriff/java-function-buildpack#18]
When i try to create a Spring Boot function i get the following error:
![image](https://user-images.githubusercontent.com/18074984/66295045-be0c9e00-e8ea-11e9-9722-b5a65f71aa39.png)

**Comment by wei-qiang** [comment]
fixed it by doing the following: git update-index --chmod=+x mvnw

**Comment by scothis** [comment]
@wei-qiang I'm glad you found the answer. If you're on a posix compliant file system (linux, Mac) then git will track the local file permissions when you add files to a commit. Using `git update-index --chmod=+x` should only be necessary from Windows since the filesystem doesn't track executability.

Let us know if you run into any other issues.
